### ISSUE TITLE
libgit2-sys 0.9.1 fails to build

### ISSUE THREAD

**Issue by Roguelazer** [rust-lang/git2-rs#483]
Tail of building libgit2 0.10.1:

```
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libssh2-sys-f7a3daef3984215c/out/include" "-I" "/usr/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/build/libgit2/src/transports/auth_ntlm.o" "-c" "libgit2/src/transports/auth_ntlm.c"
exit code: 1
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libssh2-sys-f7a3daef3984215c/out/include" "-I" "/usr/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/build/libgit2/src/transports/smart_pkt.o" "-c" "libgit2/src/transports/smart_pkt.c"
exit code: 0
exit code: 0
exit code: 0

--- stderr
fatal: not a git repository (or any of the parent directories): .git


error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libssh2-sys-f7a3daef3984215c/out/include" "-I" "/usr/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/home/vagrant/tmp/2019-10-25/cargo-audit/target/debug/build/libgit2-sys-240f97034cf48872/out/build/libgit2/src/transports/ssh.o" "-c" "libgit2/src/transports/ssh.c" with args "cc" did not execute successfully (status code exit code: 1).



warning: build failed, waiting for other jobs to finish...
```

If I chase down that file and compile it by hand:

```
$ cc "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libgit2-sys-dee9e262cbc06cf5/out/include" "-I" "libgit2/src" "-I" "libgit2/deps/http-parser" "-I" "libgit2/deps/pcre" "-I" "/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libssh2-sys-46930859b4a47eb2/out/include" "-I" "/usr/include" "-fvisibility=hidden" "-DGIT_REGEX_BUILTIN=1" "-DHAVE_STDINT_H=1" "-DHAVE_MEMMOVE=1" "-DNO_RECURSE=1" "-DNEWLINE=10" "-DPOSIX_MALLOC_THRESHOLD=10" "-DLINK_SIZE=2" "-DPARENS_NEST_LIMIT=250" "-DMATCH_LIMIT=10000000" "-DMATCH_LIMIT_RECURSION=MATCH_LIMIT" "-DMAX_NAME_SIZE=32" "-DMAX_NAME_COUNT=10000" "-DSHA1DC_NO_STANDARD_INCLUDES=1" "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"common.h\"" "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"common.h\"" "-o" "/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libgit2-sys-dee9e262cbc06cf5/out/build/libgit2/src/transports/ssh.o" "-c" "libgit2/src/transports/ssh.c"
In file included from libgit2/src/transports/ssh.c:11:
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libssh2-sys-46930859b4a47eb2/out/include/libssh2.h:276: error: redefinition of typedef ‘LIBSSH2_USERAUTH_KBDINT_PROMPT’
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libgit2-sys-dee9e262cbc06cf5/out/include/git2/transport.h:168: note: previous declaration of ‘LIBSSH2_USERAUTH_KBDINT_PROMPT’ was here
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libssh2-sys-46930859b4a47eb2/out/include/libssh2.h:282: error: redefinition of typedef ‘LIBSSH2_USERAUTH_KBDINT_RESPONSE’
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libgit2-sys-dee9e262cbc06cf5/out/include/git2/transport.h:169: note: previous declaration of ‘LIBSSH2_USERAUTH_KBDINT_RESPONSE’ was here
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libssh2-sys-46930859b4a47eb2/out/include/libssh2.h:362: error: redefinition of typedef ‘LIBSSH2_SESSION’
/home/vagrant/tmp/2019-10-25/git2-rs/target/debug/build/libgit2-sys-dee9e262cbc06cf5/out/include/git2/transport.h:167: note: previous declaration of ‘LIBSSH2_SESSION’ was here
```

FWIW the system has libssh2 1.9.0 installed but does not have any system-wide libgit2; unclear whether that's related.

**Comment by Roguelazer** [comment]
I can confirm that libgit2 0.28.3 builds with no issues from source on my platform, and if I install it, libgit2-sys builds successfully. This suggests some kind of issue with the bundled libgit2 (which seems to be 0.28.0)

**Comment by ehuss** [comment]
Which platform are you on?

This looks similar to https://github.com/libgit2/libgit2/issues/5246.

**Comment by Roguelazer** [comment]
Effectively CentOS 6, so that does look related.

Odd that 0.28.3 builds with no errors or warnings, though.

-- 
James Brown,
currently mobile

**Comment by Roguelazer** [comment]
Perhaps I misspoked about it working with 0.28.3, anyway... every HTTP operation fails with `error: couldn't fetch advisory database: git operation failed: invalid version 0 on git_proxy_options; class=Invalid (3)` which suggests either a bug or an ABI mismatch, and given the build issues I'm inclined to think the latter.

**Comment by Roguelazer** [comment]
Oh yeah, your bindings don't work with 0.28.3 at all because the number of items in `git_remote_callbacks` is different, so if this is run against 0.28.3, the structure is the wrong size and nothing works.

Bummer.

**Comment by alexcrichton** [comment]
Ah yes this library isn't guaranteed to work with w/e is on the system, it's only guarnateed to work with what's bundled because libgit2 doesn't have ABI-stable releases yet.
